version: "3.9"

services:
  web:
    image: 192.168.56.11/pecheimg/peche_app:main-20251211-1557-a167bb1
    ports:
      - "8083:80"
    environment:
      - DB_HOST=192.168.56.14
      - DB_NAME=peche
      - DB_USER=peche_user
      - DB_PASSWORD=peche_pwd
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
    networks:
      - peche_net

networks:
  peche_net:
