---
- hosts: all
  become: yes
  roles:
    - docker

- hosts: manager
  become: yes
  roles:
    - swarm

- hosts: workers
  become: yes
  roles:
    - swarm

- hosts: db
  become: yes
  roles:
    - db
